Ext.ns("Ext.ux.form");
Ext.ux.form.DateTime=Ext.extend(Ext.form.Field,{dateValidator:null,defaultAutoCreate:{tag:"input",type:"hidden"},dtSeparator:" ",hiddenFormat:"Y-m-d H:i:s",otherToNow:!0,timePosition:"right",timeValidator:null,timeWidth:100,dateFormat:"m/d/y",timeFormat:"g:i A",initComponent:function(){Ext.ux.form.DateTime.superclass.initComponent.call(this);var a=Ext.apply({},{id:this.id+"-date",format:this.dateFormat||Ext.form.DateField.prototype.format,width:this.timeWidth,selectOnFocus:this.selectOnFocus,validator:this.dateValidator,
listeners:{blur:{scope:this,fn:this.onBlur},focus:{scope:this,fn:this.onFocus}}},this.dateConfig);this.df=new Ext.form.DateField(a);this.df.ownerCt=this;delete this.dateFormat;a=Ext.apply({},{id:this.id+"-time",format:this.timeFormat||Ext.form.TimeField.prototype.format,width:this.timeWidth,selectOnFocus:this.selectOnFocus,validator:this.timeValidator,listeners:{blur:{scope:this,fn:this.onBlur},focus:{scope:this,fn:this.onFocus}}},this.timeConfig);this.tf=new Ext.form.TimeField(a);this.tf.ownerCt=
this;delete this.timeFormat;this.relayEvents(this.df,["focus","specialkey","invalid","valid"]);this.relayEvents(this.tf,["focus","specialkey","invalid","valid"]);this.on("specialkey",this.onSpecialKey,this)},onRender:function(a,b){if(!this.isRendered){Ext.ux.form.DateTime.superclass.onRender.call(this,a,b);var c;this.tableEl=c="below"===this.timePosition||"bellow"===this.timePosition?Ext.DomHelper.append(a,{tag:"table",style:"border-collapse:collapse",children:[{tag:"tr",children:[{tag:"td",style:"padding-bottom:1px",
cls:"ux-datetime-date"}]},{tag:"tr",children:[{tag:"td",cls:"ux-datetime-time"}]}]},!0):Ext.DomHelper.append(a,{tag:"table",style:"border-collapse:collapse",children:[{tag:"tr",children:[{tag:"td",style:"padding-right:4px",cls:"ux-datetime-date"},{tag:"td",cls:"ux-datetime-time"}]}]},!0);this.wrap=c.wrap({cls:"x-form-field-wrap"});this.wrap.on("mousedown",this.onMouseDown,this,{delay:10});this.df.render(c.child("td.ux-datetime-date"));this.tf.render(c.child("td.ux-datetime-time"));this.df.el.swallowEvent(["keydown",
"keypress"]);this.tf.el.swallowEvent(["keydown","keypress"]);if("side"===this.msgTarget){if(c=this.el.findParent(".x-form-element",10,!0))this.errorIcon=c.createChild({cls:"x-form-invalid-icon"});c={errorIcon:this.errorIcon,msgTarget:"side",alignErrorIcon:this.alignErrorIcon.createDelegate(this)};Ext.apply(this.df,c);Ext.apply(this.tf,c)}this.el.dom.name=this.hiddenName||this.name||this.id;this.df.el.dom.removeAttribute("name");this.tf.el.dom.removeAttribute("name");this.isRendered=!0;this.updateHidden()}},
adjustSize:Ext.BoxComponent.prototype.adjustSize,alignErrorIcon:function(){this.errorIcon.alignTo(this.tableEl,"tl-tr",[2,0])},initDateValue:function(){this.dateValue=this.otherToNow?new Date:new Date(1970,0,1,0,0,0)},clearInvalid:function(){this.df.clearInvalid();this.tf.clearInvalid()},markInvalid:function(a){this.df.markInvalid(a);this.tf.markInvalid(a)},beforeDestroy:function(){this.isRendered&&(this.wrap.removeAllListeners(),this.wrap.remove(),this.tableEl.remove(),this.df.destroy(),this.tf.destroy())},
disable:function(){if(this.isRendered)this.df.disabled=this.disabled,this.df.onDisable(),this.tf.onDisable();this.disabled=!0;this.df.disabled=!0;this.tf.disabled=!0;this.fireEvent("disable",this);return this},enable:function(){this.rendered&&(this.df.onEnable(),this.tf.onEnable());this.disabled=!1;this.df.disabled=!1;this.tf.disabled=!1;this.fireEvent("enable",this);return this},focus:function(){this.df.focus()},getPositionEl:function(){return this.wrap},getResizeEl:function(){return this.wrap},
getValue:function(){return this.dateValue?new Date(this.dateValue):""},isValid:function(){return this.df.isValid()&&this.tf.isValid()},isVisible:function(){return this.df.rendered&&this.df.getActionEl().isVisible()},onBlur:function(a){if(this.wrapClick)a.focus(),this.wrapClick=!1;a===this.df?this.updateDate():this.updateTime();this.updateHidden();this.validate();(function(){if(!this.df.hasFocus&&!this.tf.hasFocus){var a=this.getValue();String(a)!==String(this.startValue)&&this.fireEvent("change",
this,a,this.startValue);this.hasFocus=!1;this.fireEvent("blur",this)}}).defer(100,this)},onFocus:function(){if(!this.hasFocus)this.hasFocus=!0,this.startValue=this.getValue(),this.fireEvent("focus",this)},onMouseDown:function(a){if(!this.disabled)this.wrapClick="td"===a.target.nodeName.toLowerCase()},onSpecialKey:function(a,b){var c=b.getKey();c===b.TAB&&(a===this.df&&!b.shiftKey&&(b.stopEvent(),this.tf.focus()),a===this.tf&&b.shiftKey&&(b.stopEvent(),this.df.focus()),this.updateValue());c===b.ENTER&&
this.updateValue()},reset:function(){this.df.setValue(this.originalValue);this.tf.setValue(this.originalValue)},setDate:function(a){this.df.setValue(a)},setTime:function(a){this.tf.setValue(a)},setSize:function(a,b){a&&("below"===this.timePosition?(this.df.setSize(a,b),this.tf.setSize(a,b),Ext.isIE&&(this.df.el.up("td").setWidth(a),this.tf.el.up("td").setWidth(a))):(this.df.setSize(a-this.timeWidth-4,b),this.tf.setSize(this.timeWidth,b),Ext.isIE&&(this.df.el.up("td").setWidth(a-this.timeWidth-4),
this.tf.el.up("td").setWidth(this.timeWidth))))},setValue:function(a){!a&&!0===this.emptyToNow?this.setValue(new Date):(a?("number"===typeof a?a=new Date(a):"string"===typeof a&&this.hiddenFormat&&(a=Date.parseDate(a,this.hiddenFormat)),a=a?a:new Date(1970,0,1,0,0,0),a instanceof Date?(this.setDate(a),this.setTime(a),this.dateValue=new Date(Ext.isIE?a.getTime():a)):(a=a.split(this.dtSeparator),this.setDate(a[0]),a[1]&&(a[2]&&(a[1]+=a[2]),this.setTime(a[1])))):(this.setDate(""),this.setTime("")),this.updateValue())},
setVisible:function(a){a?(this.df.show(),this.tf.show()):(this.df.hide(),this.tf.hide());return this},show:function(){return this.setVisible(!0)},hide:function(){return this.setVisible(!1)},updateDate:function(){var a=this.df.getValue();a?(this.dateValue instanceof Date||(this.initDateValue(),this.tf.getValue()||this.setTime(this.dateValue)),this.dateValue.setMonth(0),this.dateValue.setFullYear(a.getFullYear()),this.dateValue.setMonth(a.getMonth(),a.getDate())):(this.dateValue="",this.setTime(""))},
updateTime:function(){var a=this.tf.getValue();a&&!(a instanceof Date)&&(a=Date.parseDate(a,this.tf.format));a&&!this.df.getValue()&&(this.initDateValue(),this.setDate(this.dateValue));this.dateValue instanceof Date&&(a?(this.dateValue.setHours(a.getHours()),this.dateValue.setMinutes(a.getMinutes()),this.dateValue.setSeconds(a.getSeconds())):(this.dateValue.setHours(0),this.dateValue.setMinutes(0),this.dateValue.setSeconds(0)))},updateHidden:function(){if(this.isRendered)this.el.dom.value=this.dateValue instanceof
Date?this.dateValue.format(this.hiddenFormat):""},updateValue:function(){this.updateDate();this.updateTime();this.updateHidden()},validate:function(){return this.df.validate()&&this.tf.validate()},renderer:function(a){var b=a.editor.dateFormat||Ext.ux.form.DateTime.prototype.dateFormat;b+=" "+(a.editor.timeFormat||Ext.ux.form.DateTime.prototype.timeFormat);return function(a){return Ext.util.Format.date(a,b)}}});Ext.reg("xdatetime",Ext.ux.form.DateTime);
